### ISSUE TITLE
about

### ISSUE THREAD

**Issue by Ouyang-maxzx** [NLaws/LinDistFlow#1]
Hello，lindistflow mathmatical expression can be provided,I want to use this lindistflow in matlab as a power flow constraint,But I haven't been able to find the correct mathematical formal。thank you

**Comment by NLaws** [comment]
I provided the reference for the model in the [README](https://github.com/NLaws/LinDistFlow#references)

**Comment by weigao-123** [comment]
Hello @NLaws, for the 3-phase LinDistFlow, what I got from the original paper [here](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7741261) shows the **negative** coefficient for the voltage drop equation:
```math
\begin{aligned}
\boldsymbol{w}_j = \boldsymbol{w}_i - \boldsymbol{M}_{P,ij} \boldsymbol{P}_{ij} - \boldsymbol{M}_{Q,ij} \boldsymbol{Q}_{ij}
\end{aligned}
```
but shows **positive** in your documentation [here](https://nlaws.github.io/LinDistFlow/dev/math/), could you confirm this, thank you!

**Comment by NLaws** [comment]
Hello @weigao-123. The Arnold et al. paper uses loads as positive values in their formulation, whereas the model in LinDistFlow.jl uses the convention that loads are negative (power injections are positive). Hence the sign differences. 

Also of note, this package has been tested against the results in the Arnold et al. paper ([here, with a note about the sign convention](https://github.com/NLaws/LinDistFlow/blob/1f9e83e7ef9a0e0ea78da0729e945ba149b09b65/test/runtests.jl#L70).

Lastly, I'll mention that the model in LinDistFlow.jl will be available in [BranchFlowModel.jl](https://github.com/NLaws/BranchFlowModel.jl) some time soon (in addition to other forms of the branch flow model).

**Comment by weigao-123** [comment]
> Hello @weigao-123. The Arnold et al. paper uses loads as positive values in their formulation, whereas the model in LinDistFlow.jl uses the convention that loads are negative (power injections are positive). Hence the sign differences.
> 
> Also of note, this package has been tested against the results in the Arnold et al. paper ([here, with a note about the sign convention](https://github.com/NLaws/LinDistFlow/blob/1f9e83e7ef9a0e0ea78da0729e945ba149b09b65/test/runtests.jl#L70).
> 
> Lastly, I'll mention that the model in LinDistFlow.jl will be available in [BranchFlowModel.jl](https://github.com/NLaws/BranchFlowModel.jl) some time soon (in addition to other forms of the branch flow model).

I see, thank you for the clarification!
